#pragma once

#define GUI_WINDOW_FILL_COLOR 0xe0e0e
#define GUI_WINDOW_BORDER_COLOR 0x2a2a2a
#define GUI_WINDOW_TEXT_COLOR 0xa0b4c8
#define GUI_WINDOW_ACTIVE_BORDER_COLOR 0x8cb4dc

#define GUI_BUTTON_FILL_COLOR 0x1a1a1a
#define GUI_BUTTON_HOVER_COLOR 0x2a2a2a
#define GUI_BUTTON_PRESS_COLOR 0x404040
#define GUI_BUTTON_BORDER_COLOR 0x2a2a2a
#define GUI_BUTTON_TEXT_COLOR 0xa0b4c8